### ISSUE TITLE
Choice of `Open with`

### ISSUE THREAD

**Issue by NeeRaj-2401** [Bnyro/FindX#4]
<img src="https://user-images.githubusercontent.com/88180887/218412992-017da49c-4ab5-4f5c-8087-4d3c931d07a3.jpg" width="25%">

In the top right corner of results. Can we have an option to choose alternatives(piped/indivious/youtube) or instance of these services.

Reason: in my region nitter.kavin.rocks works fine but nitter.net does not.
Hence choosing the well suited instance or open in original. Such things would be helpful.

**Comment by Bnyro** [comment]
I guess it would be the best if the person hosting it just picks some working instances (my bad, I should have tested all of them before). I'm gonna update the ones not working well asap.
However I don't see a reason to let users choose the instance they use like that, also because it would require collecting tons of available instances for each service.

**Comment by NeeRaj-2401** [comment]
Yes, you are right. I think Atleast an option to **open in original site** in case of any instance side error.
